import { pgTable, uuid, varchar } from "drizzle-orm/pg-core";
import { rolesEnum, timestamps } from "./common";

const baseUser = {
  id: uuid("id").primaryKey().defaultRandom(),
  first_name: varchar("first_name", { length: 255 }).notNull(),
  last_name: varchar("last_name", { length: 255 }).notNull(),
  password: varchar("password", { length: 255 }).notNull(), //generated by the system
  role: rolesEnum().notNull(),
  ...timestamps,
};

export const students = pgTable("students", {
  username: varchar("username", { length: 255 }).unique().notNull(), //generated by the system
  email: varchar("email", { length: 255 }).unique().notNull(), //required in front - free session
  ...baseUser,
});

export const professors = pgTable("professors", {
  username: varchar("username", { length: 255 }).unique().notNull(), //generated by the system
  email: varchar("email", { length: 255 }).unique().notNull(), //required in front - free session

  ...baseUser,
});
